import Footer from "@/components/Home/Footer";
import Header from "@/components/Home/Header";
import { ThemeProvider } from "@/provider/ThemeProvider";

import type { Metadata } from "next";
import { Epilogue, Inter } from "next/font/google";
import "./globals.css";

const epilogue = Epilogue({
  variable: "--font-family-topic",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-family-subtopic",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jewelry App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${epilogue.variable} ${inter.variable}  bg-dark h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
